source 'https://github.com/ZGComponent-based/ZGSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end
end


target 'ZGUIDemo' do
    pod 'ZGUI', :path => '../' 
    pod 'ZGNetwork', '1.0.0'
    pod 'ZGCore', '1.0.0'
end
